class Dish {
  final String nameEn;
  final String nameTh;
  final String img;
  final String category;
  final int id;

  Dish({this.nameEn, this.nameTh, this.img, this.category, this.id});
}

List<Dish> dishes = [
  Dish(
    nameEn: "Fried Rice",
    nameTh: "ข้าวผัด",
    img: "khao-pad.jpg",
    category: "rice",
    id: 1,
  ),
  Dish(
    nameEn: "Pad Thai",
    nameTh: "ผัดไทย",
    img: "pad-thai.jpg",
    category: "noodle",
    id: 2,
  ),
  Dish(
    nameEn: 'Tom Yum',
    nameTh: 'ต้มยำ',
    img: 'tom-yum.jpg',
    category: 'soup',
    id: 3,
  ),
  Dish(
    nameEn: 'Papaya salad',
    nameTh: 'ส้มตำไทย',
    img: 'som-tam-thai.jpg',
    category: 'other',
    id: 4,
  ),
  Dish(
    nameEn: 'Phad Krapao (minced meat)',
    nameTh: 'ผัดกะเพรา',
    img: 'phad-krapao.jpg',
    category: 'rice',
    id: 5,
  ),
  Dish(
    nameEn: 'Panang (curry)',
    nameTh: 'พะแนง',
    img: 'panang.jpg',
    category: 'rice',
    id: 6,
  ),
  Dish(
    nameEn: 'Red Pork',
    nameTh: 'ข้าวหมูแดง',
    img: 'khao-moo-daeng.jpg',
    category: 'rice',
    id: 7,
  ),
  Dish(
    nameEn: 'Wide Noodle Soup',
    nameTh: 'ก๋วยเตี๋ยวน้ำ',
    img: 'guay-teow-nam.jpg',
    category: 'soup',
    id: 8,
  ),
  Dish(
    nameEn: 'Larb (minced meat salad)',
    nameTh: 'ลาบอีสาน',
    img: 'larb.jpg',
    category: 'other',
    id: 9,
  ),
  Dish(
    nameEn: 'Fried Wide Noodle',
    nameTh: 'ผัดซีอิ๊ว',
    img: 'pad-see-eiw.jpg',
    category: 'noodle',
    id: 10,
  ),
  Dish(
    nameEn: 'Green Curry',
    nameTh: 'แกงเขียวหวาน',
    img: 'gaeng-keow-wan.jpg',
    category: 'soup',
    id: 11,
  ),
  Dish(
    nameEn: 'Cashew Chicken',
    nameTh: 'ไก่ผัดเม็ดมะม่วงหิมพานต์',
    img: 'gai-med-ma-muang.jpg',
    category: 'rice',
    id: 12,
  ),
  Dish(
    nameEn: 'Stuffed Omelette',
    nameTh: 'ไข่ยัดไส้',
    img: 'khai-yat-sai.jpg',
    category: 'other',
    id: 13,
  ),
  Dish(
    nameEn: 'Chicken Biryani',
    nameTh: 'ข้าวหมกไก่',
    img: 'khao-mok-gai.jpg',
    category: 'rice',
    id: 14,
  ),
  Dish(
    nameEn: 'Poached/boiled Chicken',
    nameTh: 'ข้าวมันไก่',
    img: 'khao-man-gai.jpg',
    category: 'rice',
    id: 15,
  ),
  Dish(
    nameEn: 'Crispy Pork',
    nameTh: 'ข้าวหมูกรอบ',
    img: 'khao-moo-krop .jpg',
    category: 'rice',
    id: 16,
  ),
  Dish(
    nameEn: 'Red Roasted Duck',
    nameTh: 'ข้าวหน้าเป็ด',
    img: 'khao-na-pet.jpg',
    category: 'rice',
    id: 17,
  ),
  Dish(
    nameEn: 'Sticky Rice',
    nameTh: 'ข้าวเหนียว',
    img: 'khao-niao.jpg',
    category: 'rice',
    id: 18,
  ),
  Dish(
    nameEn: 'Egg Noodle Soup with Red Pork',
    nameTh: 'บะหมี่หมูแดง',
    img: 'bami-moo-daeng .jpg',
    category: 'noodle',
    id: 19,
  ),
  Dish(
    nameEn: 'Boat Noodle',
    nameTh: 'ก๋วยเตี๋ยวเรือ',
    img: 'kuai-tiao-ruea.jpg',
    category: 'noodle',
    id: 20,
  ),
  Dish(
    nameEn: 'Nam Tok',
    nameTh: 'เนื้อย่างน้ำตก',
    img: 'nam-tok.jpg',
    category: 'other',
    id: 21,
  ),
  Dish(
    nameEn: 'Fish-Papaya Salad',
    nameTh: 'ส้มตำปลาร้า',
    img: 'som-tam-pla.jpg',
    category: 'other',
    id: 22,
  ),
  Dish(
    nameEn: 'Glass Noodle Salad',
    nameTh: 'ยำวุ้นเส้น ',
    img: 'yam-wun-sen.jpg',
    category: 'noodle',
    id: 23,
  ),
  Dish(
    nameEn: 'Ginger Chicken',
    nameTh: 'ไก่ผัดขิง',
    img: 'kai-phat-khing.jpg',
    category: 'other',
    id: 24,
  ),
  Dish(
    nameEn: 'Grilled Chicken',
    nameTh: 'ไก่ย่าง',
    img: 'gai-yaang.jpg',
    category: 'other',
    id: 25,
  ),
  Dish(
    nameEn: 'Grilled Pork',
    nameTh: 'หมูย่าง ',
    img: 'moo-yang.jpg',
    category: 'other',
    id: 26,
  ),
  Dish(
    nameEn: 'Pork & Sticky Rice Sausage',
    nameTh: 'ไส้กรอกอีสาน',
    img: 'sai-krok-isaan.jpg',
    category: 'other',
    id: 27,
  ),
  Dish(
    nameEn: 'Sun Dried Beef',
    nameTh: 'เนื้อแดดเดียวกะเพราทอด',
    img: 'nuea-daet-diao-kaphrao-thot.jpg',
    category: 'other',
    id: 28,
  ),
  Dish(
    nameEn: 'Mango with Sticky Rice',
    nameTh: 'ข้าวเหนียวมะม่วง',
    img: 'khao-niao-mamuang.jpg',
    category: 'dessert',
    id: 29,
  ),
  Dish(
    nameEn: 'Deepfried Banana',
    nameTh: 'กล้วยทอด',
    img: 'kluai-thot.jpg',
    category: 'dessert',
    id: 30,
  ),
  Dish(
    nameEn: 'Banana Roti (pancake)',
    nameTh: 'โรตีกล้วย',
    img: 'roti-kluai.jpg',
    category: 'dessert',
    id: 31,
  ),
  Dish(
    nameEn: 'Egg Tart',
    nameTh: 'ทาร์ตไข่',
    img: 'that-khai.jpg',
    category: 'dessert',
    id: 32,
  ),
  Dish(
    nameEn: 'Pearls and Beans in Milk',
    nameTh: 'สาคูถั่วดำ ',
    img: 'sakhu-thua-dam.jpg',
    category: 'dessert',
    id: 33,
  ),
  Dish(
    nameEn: 'Krating Daeng (Red Bull)',
    nameTh: 'กระทิงแดง',
    img: 'krating-daeng.jpg',
    category: 'drink',
    id: 34,
  ),
  Dish(
    nameEn: 'Thai Ice Tea',
    nameTh: 'ชาเย็น',
    img: 'cha-yen.jpg',
    category: 'drink',
    id: 35,
  ),
];
